const RECEBO_WA = "5491138850128";

const PRODUCTOS = [
{
    id: 'rancheroo',
    nombre: 'Rancheroo',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$37.000',
    desc: 'Mate artesanal con terminado rústico y carácter. Ideal para el mate intenso de todos los días.',
    descLarga: 'El Rancheroo es el mate ideal para quienes buscan carácter y presencia. Acabado rústico con terminado artesanal, robusto y cómodo en la mano. Perfecto para el mate de todos los días.',
    img: 'img/catalogo/Rancheroo/94da91a4-2f8c-44a2-8424-1816a110b4ed.jpg',
    imgs: ['img/catalogo/Rancheroo/d420828f-fef7-45b4-94ca-619a2ab0caa2.jpg','img/catalogo/Rancheroo/IMG_1025.jpg','img/catalogo/Rancheroo/IMG_1026.jpg','img/catalogo/Rancheroo/IMG_1027.jpg','img/catalogo/Rancheroo/IMG_1028.jpg','img/catalogo/Rancheroo/IMG_1029.jpg'],
    badge: 'Destacado',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Rancheroo'
  },
{
    id: 'imperial-algarrobo',
    nombre: 'Imperial Raíz de Algarrobo',
    categoria: 'mate',
    catLabel: 'Madera nativa',
    precio: '$21.000',
    desc: 'Tallado en raíz de algarrobo nativo. Cada pieza es única por la veta natural de la madera.',
    descLarga: 'Tallado a mano en raíz de algarrobo nativo. La veta natural de la madera hace que cada pieza sea absolutamente única. Un mate con identidad propia.',
    img: 'img/catalogo/Algarrobo Raiz/IMG_8616.jpg',
    imgs: ['img/catalogo/Algarrobo Raiz/IMG_8618.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Imperial%20Ra%C3%ADz%20de%20Algarrobo'
  },
{
    id: 'acero-urbano',
    nombre: 'Acero Urbano',
    categoria: 'mate',
    catLabel: 'Acero inoxidable',
    precio: '$12.300',
    desc: 'Mate de acero inoxidable con diseño moderno. Liviano, resistente y de fácil limpieza.',
    descLarga: 'El Acero Urbano combina funcionalidad y diseño moderno. Fabricado en acero inoxidable, es liviano, resistente y de fácil limpieza. Ideal para llevar a todos lados.',
    img: 'img/catalogo/Acero Urbano/IMG_1009.jpg',
    imgs: ['img/catalogo/Acero Urbano/IMG_1010.jpg','img/catalogo/Acero Urbano/IMG_1012.jpg','img/catalogo/Acero Urbano/IMG_1013.jpg','img/catalogo/Acero Urbano/IMG_1014.jpg','img/catalogo/Acero Urbano/IMG_8659.jpg','img/catalogo/Acero Urbano/IMG_8663.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Acero%20Urbano'
  },
{
    id: 'imperial-noble-bolitas',
    nombre: 'Imperial Noble con Bolitas',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$42.000',
    desc: 'Acabado con bolitas decorativas en el aro. Diseño noble y elegante, ideal para regalo.',
    descLarga: 'El Imperial Noble con Bolitas es una de las piezas más elegantes del catálogo. Las bolitas decorativas en el aro le dan un carácter distinguido. Ideal para regalo o para quienes buscan algo especial.',
    img: 'img/catalogo/Imperial Noble con bolitas/IMG_1004.jpg',
    imgs: ['img/catalogo/Imperial Noble con bolitas/IMG_1005.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1049.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1050.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1052.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1054.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1055.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1056.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1057.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1058.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1059.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1060.jpg','img/catalogo/Imperial Noble con bolitas/IMG_1061.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Imperial%20Noble%20con%20Bolitas'
  },
{
    id: 'torpedo-noble-bolitas',
    nombre: 'Torpedo Noble con Bolitas',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$45.000',
    desc: 'Forma torpedo con terminado noble y bolitas artesanales. Gran capacidad y presencia.',
    descLarga: 'Forma torpedo con terminado noble y bolitas artesanales en el aro. Gran capacidad y presencia en la mano. Para quienes prefieren un mate generoso.',
    img: 'img/catalogo/Torpedo Noble Con Bolitas/IMG_1002.jpg',
    imgs: ['img/catalogo/Torpedo Noble Con Bolitas/IMG_1003.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Noble%20con%20Bolitas'
  },
{
    id: 'torpedo-crudo',
    nombre: 'Torpedo Crudo',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$62.300',
    desc: 'Acabado crudo sin pintura, conservando la textura natural del material. Rústico y auténtico.',
    descLarga: 'El Torpedo Crudo conserva el acabado natural sin pintura ni tratamientos artificiales. Textura genuina, rústica y auténtica. Para quienes valoran lo natural sobre todo.',
    img: 'img/catalogo/Torpedo Crudo/IMG_1071.jpg',
    imgs: ['img/catalogo/Torpedo Crudo/IMG_1072.jpg','img/catalogo/Torpedo Crudo/IMG_1073.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Crudo'
  },
{
    id: 'torpedo-plata',
    nombre: 'Torpedo Plata Premium',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$45.300',
    desc: 'Acabado en plata premium con detalles de lujo. El más elegante de la familia torpedo.',
    descLarga: 'El Torpedo Plata Premium es el más distinguido de la familia. Acabado en plata con detalles de lujo que lo convierten en una pieza de colección.',
    img: 'img/catalogo/Torpedo Plata Premium/IMG_0999.jpg',
    imgs: ['img/catalogo/Torpedo Plata Premium/IMG_1001.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Plata%20Premium'
  },
{
    id: 'torpedo-cincelado',
    nombre: 'Torpedo Cincelado',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$38.500',
    desc: 'Trabajo de cincelado artesanal en la superficie. Textura única hecha a mano.',
    descLarga: 'Cada Torpedo Cincelado es trabajado a mano con técnica de cincelado artesanal. La textura resultante es única en cada pieza.',
    img: 'img/catalogo/Torpedo Cincelado/IMG_1045.jpg',
    imgs: ['img/catalogo/Torpedo Cincelado/IMG_1046.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Cincelado'
  },
{
    id: 'pampa-diario',
    nombre: 'Pampa Diario',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$16.000',
    desc: 'El compañero ideal para el mate de todos los días. Robusto, cómodo y de buena capacidad.',
    descLarga: 'El Pampa Diario es el compañero perfecto para el mate cotidiano. Diseño robusto, capacidad generosa y comodidad en la mano. Sin vueltas.',
    img: 'img/catalogo/Pampa Diario/IMG_1015.jpg',
    imgs: ['img/catalogo/Pampa Diario/IMG_1018.jpg','img/catalogo/Pampa Diario/IMG_1021.jpg','img/catalogo/Pampa Diario/IMG_1023.jpg','img/catalogo/Pampa Diario/IMG_8670.jpg','img/catalogo/Pampa Diario/IMG_8672.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Pampa%20Diario'
  },
{
    id: 'imperial-roma',
    nombre: 'Imperial Roma',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$43.700',
    desc: 'Diseño imperial con inspiración clásica. Acabado refinado y gran presencia en la mano.',
    descLarga: 'El Imperial Roma toma inspiración del clasicismo para crear un mate de acabado refinado y gran presencia. Una pieza que impresiona desde el primer vistazo.',
    img: 'img/catalogo/Imperial Roma/IMG_1037.jpg',
    imgs: ['img/catalogo/Imperial Roma/IMG_1038.jpg','img/catalogo/Imperial Roma/IMG_1040.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Imperial%20Roma'
  },
{
    id: 'mate-galleta',
    nombre: 'Mate Galleta',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$20.000',
    desc: 'Forma galleta clásica, amplia y cómoda. El preferido para el mate dulce y generoso.',
    descLarga: 'La forma galleta es la más tradicional de Argentina. Amplia, cómoda y con gran capacidad. El mate ideal para los que cebar es un arte.',
    img: 'img/catalogo/Mate Galleta/IMG_9469.jpg',
    imgs: ['img/catalogo/Mate Galleta/IMG_9476.jpg','img/catalogo/Mate Galleta/IMG_9478.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Mate%20Galleta'
  },
{
    id: 'mate-criollo',
    nombre: 'Mate Criollo',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$16.200',
    desc: 'El clásico criollo con identidad argentina. Simple, funcional y con mucha personalidad.',
    descLarga: 'El Mate Criollo es un homenaje a la tradición. Simple, funcional y con la personalidad que solo tiene lo auténtico. Para quienes aman lo clásico sin vueltas.',
    img: 'img/catalogo/Mate Criollo/IMG_1041.jpg',
    imgs: ['img/catalogo/Mate Criollo/IMG_1042.jpg','img/catalogo/Mate Criollo/IMG_7338.jpeg','img/catalogo/Mate Criollo/IMG_7339.jpeg','img/catalogo/Mate Criollo/IMG_7343.jpeg','img/catalogo/Mate Criollo/IMG_7345.jpeg','img/catalogo/Mate Criollo/IMG_7448.JPG','img/catalogo/Mate Criollo/IMG_7452.JPG'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Mate%20Criollo'
  },
{
    id: 'torpedo-serpental',
    nombre: 'Torpedo Serpental',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$38.600',
    desc: 'Diseño serpental con curvas trabajadas artesanalmente. Llamativo y cómodo en la mano.',
    descLarga: 'El Torpedo Serpental tiene curvas trabajadas artesanalmente que lo hacen llamativo y cómodo. Una pieza de arte funcional.',
    img: 'img/catalogo/Torpedo Serpental/IMG_9456.jpg',
    imgs: ['img/catalogo/Torpedo Serpental/IMG_9459.jpg','img/catalogo/Torpedo Serpental/IMG_9461.jpg','img/catalogo/Torpedo Serpental/WhatsApp Image 2026-07-09 at 11.14.31.jpeg','img/catalogo/Torpedo Serpental/WhatsApp Image 2026-07-09 at 11.14.36.jpeg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Serpental'
  },
{
    id: 'ranchero-argentum',
    nombre: 'Mate Ranchero Argentum',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$38.000',
    desc: 'Versión Argentum del clásico ranchero. Detalles plateados y acabado artesanal de primera.',
    descLarga: 'El Ranchero Argentum es la versión premium del clásico. Detalles plateados y acabado artesanal de primera calidad. Para quienes quieren el clásico pero con algo más.',
    img: 'img/catalogo/Mate Ranchero Argentum/78adf2ab-113d-4c7d-9471-2825fd1c7cb7.jpg',
    imgs: ['img/catalogo/Mate Ranchero Argentum/f4f0e5d5-3333-4fb9-baf6-16f3128b21f0.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Mate%20Ranchero%20Argentum'
  },
{
    id: 'imperial-animal-print',
    nombre: 'Imperial Animal Print',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$42.300',
    desc: 'Diseño animal print exclusivo sobre cuerpo imperial. Para quienes buscan diferenciarse.',
    descLarga: 'El Imperial Animal Print combina la clásica forma imperial con un diseño animal print exclusivo. Una pieza que llama la atención y es conversación garantizada.',
    img: 'img/catalogo/Imperial animal print/IMG_1043.jpg',
    imgs: ['img/catalogo/Imperial animal print/IMG_1044.jpg'],
    badge: 'Único',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Imperial%20Animal%20Print'
  },
{
    id: 'imperial-noble',
    nombre: 'Imperial Noble',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$28.600',
    desc: 'El clásico imperial en su versión noble. Equilibrio perfecto entre tradición y elegancia.',
    descLarga: 'El Imperial Noble es el equilibrio perfecto entre tradición y elegancia. Forma imperial clásica con acabado noble. Un mate que nunca pasa de moda.',
    img: 'img/catalogo/Imperial Noble/IMG_1062.jpg',
    imgs: ['img/catalogo/Imperial Noble/IMG_1064.jpg','img/catalogo/Imperial Noble/IMG_7330.jpeg','img/catalogo/Imperial Noble/IMG_7331.jpeg','img/catalogo/Imperial Noble/IMG_7464.jpg','img/catalogo/Imperial Noble/WhatsApp Image 2026-07-09 at 11.12.21.jpeg','img/catalogo/Imperial Noble/WhatsApp Image 2026-07-09 at 11.16.34.jpeg','img/catalogo/Imperial Noble/WhatsApp Image 2026-07-09 at 11.18.26.jpeg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Imperial%20Noble'
  },
{
    id: 'torpedo-acorazado',
    nombre: 'Torpedo Acorazado',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$39.800', // PENDIENTE — precio no disponible en lista de precios
    desc: 'Diseño torpedo con blindaje artesanal. Robusto, con carácter y acabado único.',
    descLarga: 'El Torpedo Acorazado tiene un diseño robusto con blindaje artesanal. Carácter y acabado únicos. Consultanos por precio y disponibilidad.',
    img: 'img/catalogo/Torpedo acorazado/IMG_7362.jpeg',
    imgs: ['img/catalogo/Torpedo acorazado/IMG_7415.JPG','img/catalogo/Torpedo acorazado/IMG_7421.JPG'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Acorazado'
  },
{
    id: 'torpedo-clasico',
    nombre: 'Torpedo Clásico',
    categoria: 'mate',
    catLabel: 'Mate artesanal',
    precio: '$25.000', // PENDIENTE — precio no disponible en lista de precios
    desc: 'La versión clásica de la forma torpedo. El más vendido de la familia, por algo será.',
    descLarga: 'El Torpedo Clásico es el más vendido de la familia por su equilibrio entre tamaño, comodidad y precio. Consultanos por precio y disponibilidad.',
    img: 'img/catalogo/Torpedo Clasico/IMG_1030.jpg',
    imgs: ['img/catalogo/Torpedo Clasico/IMG_1031.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Torpedo%20Cl%C3%A1sico'
  },
{
    id: 'termo-media-manija',
    nombre: 'Termo Media Manija',
    categoria: 'termo',
    catLabel: 'Termo',
    precio: '$25.400',
    desc: 'Termo con media manija ergonómica. Conserva el calor hasta 12 horas.',
    descLarga: 'Termo con media manija ergonómica. Cuerpo de acero inoxidable, conserva el calor hasta 12 horas. Pico vertedor seguro y cómodo.',
    img: 'img/catalogo/Termo Media Manija/IMG_1099.PNG',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Termo%20Media%20Manija'
  },
{
    id: 'stanley-sistem',
    nombre: 'Termo Sistem (Stanley)',
    categoria: 'termo',
    catLabel: 'Termo',
    precio: '$42.400',
    desc: 'Sistema tipo Stanley en llamativo color naranja. Robusto, de pico y con excelente retención térmica.',
    descLarga: 'Sistema tipo Stanley en color naranja. Diseño robusto con pico vertedor de gran calibre. Excelente retención térmica para todo el día en el campo o la ciudad.',
    img: 'img/catalogo/Stanley Sistem/IMG_9329.jpg',
    imgs: ['img/catalogo/Stanley Sistem/IMG_9330.jpg'],
    badge: 'Naranja',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Termo%20Sistem%20Stanley'
  },
{
    id: 'termo-simil-stanley',
    nombre: 'Termo Simil Stanley',
    categoria: 'termo',
    catLabel: 'Termo',
    precio: '$42.400',
    desc: 'Diseño inspirado en Stanley con excelente calidad. Ideal para el campo o el trabajo.',
    descLarga: 'Diseño inspirado en Stanley con la calidad que caracteriza a Recebo. Pico vertedor, cuerpo robusto y retención térmica de primera. Para el campo, la ruta o el trabajo.',
    img: 'img/catalogo/Termo Simil Stanley/IMG_1100.jpg',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Termo%20Simil%20Stanley'
  },
{
    id: 'termo-bala',
    nombre: 'Termo Bala',
    categoria: 'termo',
    catLabel: 'Termo',
    precio: '$22.300',
    desc: 'Diseño bala compacto y liviano. Perfecto para llevar a todos lados sin ocupar espacio.',
    descLarga: 'El Termo Bala es compacto, liviano y fácil de transportar. Perfecto para quienes necesitan su termo siempre a mano sin que ocupe demasiado espacio.',
    img: 'img/catalogo/Termo Bala/WhatsApp Image 2026-06-08 at 11.14.18.jpeg',
    imgs: ['img/catalogo/Termo Bala/WhatsApp Image 2026-06-08 at 11.14.18.jpeg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Termo%20Bala'
  },
{
    id: 'stanley-messi',
    nombre: 'Termo Stanley Messi Miami',
    categoria: 'termo',
    catLabel: 'Termo',
    precio: '$40.200',
    desc: 'Edición especial Inter Miami con el diseño de Messi. Coleccionable y funcional.',
    descLarga: 'Edición especial Inter Miami con el diseño de Leo Messi. Coleccionable y completamente funcional. Para los fanáticos del mate y del fútbol.',
    img: 'img/catalogo/Termo Stanley Messi/IMG_9496.jpg',
    imgs: ['img/catalogo/Termo Stanley Messi/IMG_9506.jpg','img/catalogo/Termo Stanley Messi/IMG_9515.jpg'],
    badge: 'Edición especial',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Termo%20Stanley%20Messi'
  },
{
    id: 'bombillon-mundialero',
    nombre: 'Bombillón Mundialero',
    categoria: 'bombilla',
    catLabel: 'Bombilla',
    precio: '$29.000',
    desc: 'Bombillón de gran calibre con diseño mundialero. Filtro amplio para yerbas gruesas.',
    descLarga: 'Bombillón de gran calibre con diseño mundialero exclusivo. Filtro amplio ideal para yerbas gruesas. Una pieza que suma estilo al ritual.',
    img: 'img/catalogo/Bombillon MUNDIALERO/IMG_1087.PNG',
    imgs: ['img/catalogo/Bombillon MUNDIALERO/IMG_1088.PNG','img/catalogo/Bombillon MUNDIALERO/IMG_1089.PNG','img/catalogo/Bombillon MUNDIALERO/IMG_1090.PNG','img/catalogo/Bombillon MUNDIALERO/IMG_1091.PNG','img/catalogo/Bombillon MUNDIALERO/IMG_1092.PNG'],
    badge: 'Mundialero',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Bombill%C3%B3n%20Mundialero'
  },
{
    id: 'bombillon-guardia',
    nombre: 'Bombillón Guardia',
    categoria: 'bombilla',
    catLabel: 'Bombilla',
    precio: '$28.300',
    desc: 'Bombillón con filtro tipo guardia. Ideal para yerbas finas sin que pasen residuos.',
    descLarga: 'El Bombillón Guardia tiene un filtro especial tipo guardia que retiene los residuos más finos. Perfecto para yerbas de corte fino.',
    img: 'img/catalogo/Bombillon Guardia/IMG_1093.PNG',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Bombill%C3%B3n%20Guardia'
  },
{
    id: 'bombilla-inox',
    nombre: 'Bombilla Básica Inox',
    categoria: 'bombilla',
    catLabel: 'Bombilla',
    precio: '$7.500',
    desc: 'Bombilla de acero inoxidable. Resistente, fácil de limpiar y compatible con cualquier mate.',
    descLarga: 'Bombilla de acero inoxidable de alta resistencia. Fácil de limpiar, duradera y compatible con cualquier tipo de mate. La opción confiable de siempre.',
    img: 'img/catalogo/Bombilla Inox/IMG_1086.PNG',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Bombilla%20B%C3%A1sica%20Inox'
  },
{
    id: 'pava-basica',
    nombre: 'Pava Básica Matera',
    categoria: 'pava',
    catLabel: 'Pava matera',
    precio: '$38.000',
    desc: 'Pava matera de acero inoxidable. Pico fino para cebar con precisión y sin quemarse.',
    descLarga: 'Pava matera de acero inoxidable con pico fino especialmente diseñado para cebar con precisión. Mango ergonómico y construcción segura.',
    img: 'img/catalogo/Pava matera BÁSICA/IMG-20260604-WA0163.jpg',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Pava%20B%C3%A1sica%20Matera'
  },
{
    id: 'pava-premium',
    nombre: 'Pava Premium Matera',
    categoria: 'pava',
    catLabel: 'Pava matera',
    precio: '$58.700',
    desc: 'Pava premium con terminado de lujo. Pico largo y cuerpo ergonómico para el cebador exigente.',
    descLarga: 'La Pava Premium Matera es para el cebador más exigente. Terminado de lujo, pico largo de precisión y cuerpo ergonómico que facilita el control del agua.',
    img: 'img/catalogo/Pava premium matera/IMG_1082.jpg',
    imgs: ['img/catalogo/Pava premium matera/IMG_1083.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Pava%20Premium%20Matera'
  },
{
    id: 'yerbas',
    nombre: 'Yerbas Seleccionadas',
    categoria: 'yerba',
    catLabel: 'Yerba',
    precio: 'Desde $12.500',
    desc: 'Baldo, Canarias Tradicional, Edición Especial, Serena y Té Verde. Consultanos la variedad.',
    descLarga: 'Selección de yerbas curadas con criterio mateador: Baldo, Canarias Tradicional, Canarias Edición Especial, La Serena y Té Verde. Consultanos por disponibilidad de variedades y precios.',
    img: 'img/catalogo/Yerbas/images (27).jpeg',
    imgs: ['img/catalogo/Yerbas/images (28).jpeg','img/catalogo/Yerbas/images (29).jpeg','img/catalogo/Yerbas/images (30).jpeg','img/catalogo/Yerbas/IMG_1096.PNG','img/catalogo/Yerbas/whatsapp-image-2022-07-23-at-7-03-47-pm-11-e6e733c77326909de416586143679742-480-0.webp'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20las%20yerbas%20disponibles'
  },
{
    id: 'matera-eco',
    nombre: 'Matera Eco',
    categoria: 'matera',
    catLabel: 'Matera',
    precio: '$15.200',
    desc: 'Matera ecológica con compartimento para termo y accesorios. Práctica y sustentable.',
    descLarga: 'La Matera Eco es práctica y sustentable. Con compartimento para termo, mate y accesorios. Liviana y resistente para llevar a todos lados.',
    img: 'img/catalogo/Matera Eco/IMG_1101.PNG',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Matera%20Eco'
  },
{
    id: 'matera-galope',
    nombre: 'Matera Galope',
    categoria: 'matera',
    catLabel: 'Matera',
    precio: '$42.000',
    desc: 'Matera de cuero con diseño galope. Espaciosa, elegante y con múltiples bolsillos.',
    descLarga: 'La Matera Galope es de cuero con diseño galope. Espaciosa, elegante y con múltiples bolsillos internos para todo lo que necesitás. La compañera perfecta para el mateador completo.',
    img: 'img/catalogo/Matera Galope/IMG_1065.jpg',
    imgs: ['img/catalogo/Matera Galope/IMG_1066.jpg','img/catalogo/Matera Galope/IMG_9439.jpg','img/catalogo/Matera Galope/IMG_9441.jpg','img/catalogo/Matera Galope/IMG_9445.jpg'],
    badge: 'Premium',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Matera%20Galope'
  },
{
    id: 'matera-croco',
    nombre: 'Matera Croco',
    categoria: 'matera',
    catLabel: 'Matera',
    precio: '$16.200',
    desc: 'Diseño texturizado tipo cocodrilo. Llamativa y resistente, ideal para llevar en el auto.',
    descLarga: 'La Matera Croco tiene textura tipo cocodrilo que la hace llamativa y resistente al mismo tiempo. Ideal para el auto, el trabajo o donde sea.',
    img: 'img/catalogo/Matera Croco/IMG_1098.PNG',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Matera%20Croco'
  },
{
    id: 'yerbera-base',
    nombre: 'Yerbera Base',
    categoria: 'accesorio',
    catLabel: 'Yerbera',
    precio: '$10.500',
    desc: 'Yerbera de acero con base firme. Tapa hermética y boca amplia para cargar sin derramar.',
    descLarga: 'Yerbera de acero con base firme y tapa hermética. Boca amplia que facilita la carga sin derramar. Para quienes cuidan cada detalle del ritual.',
    img: 'img/catalogo/Yerbera Base/IMG_1068.jpg',
    imgs: ['img/catalogo/Yerbera Base/IMG_1069.jpg','img/catalogo/Yerbera Base/IMG_1070.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Yerbera%20Base'
  },
{
    id: 'yerbera-cuerina',
    nombre: 'Yerbera de Cuerina',
    categoria: 'accesorio',
    catLabel: 'Yerbera',
    precio: '$8.600',
    desc: 'Recubrimiento de cuerina suave y resistente. Con aro metálico decorativo y tapa segura.',
    descLarga: 'La Yerbera de Cuerina tiene un recubrimiento suave y resistente con aro metálico decorativo. Tapa segura para mantener la yerba en condiciones.',
    img: 'img/catalogo/Yerbera Cuerina/IMG_1074.jpg',
    imgs: ['img/catalogo/Yerbera Cuerina/IMG_1075.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Yerbera%20de%20Cuerina'
  },
{
    id: 'portamate-cuero',
    nombre: 'Portamate Galope (Cuero)',
    categoria: 'accesorio',
    catLabel: 'Portamate',
    precio: '$21.200',
    desc: 'Portamate de cuero genuino con funda protectora. Para llevar tu mate sin golpes ni rayones.',
    descLarga: 'Portamate de cuero genuino con diseño galope. Funda protectora que acompaña perfecto a cualquier mate. Llevalo sin miedo a golpes ni rayones.',
    img: 'img/catalogo/Portamate cuero/IMG_1033.jpg',
    imgs: ['img/catalogo/Portamate cuero/IMG_1034.jpg','img/catalogo/Portamate cuero/IMG_1035.jpg','img/catalogo/Portamate cuero/IMG_1036.jpg','img/catalogo/Portamate cuero/IMG_1047.jpg','img/catalogo/Portamate cuero/IMG_1048.jpg','img/catalogo/Portamate cuero/IMG_9446.jpg','img/catalogo/Portamate cuero/IMG_9449.jpg'],
    badge: 'Cuero',
    badgeVariant: 'gold',
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Portamate%20de%20Cuero'
  },
{
    id: 'portamate-eco',
    nombre: 'Portamate Ecocuero',
    categoria: 'accesorio',
    catLabel: 'Portamate',
    precio: '$12.000',
    desc: 'Portamate de ecocuero resistente y económico. Protección completa para tu mate favorito.',
    descLarga: 'Portamate de ecocuero resistente y accesible. Protección completa para cualquier mate. La opción práctica sin renunciar al estilo.',
    img: 'img/catalogo/Portamate Ecocuero/67014797-2658-4068-afc7-c56e67b0c37e.jpg',
    imgs: [],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Portamate%20Ecocuero'
  },
{
    id: 'mate-listo',
    nombre: 'Mate Listo',
    categoria: 'accesorio',
    catLabel: 'Set completo',
    precio: '$28.700',
    desc: 'Kit completo listo para matear: mate + bombilla + yerba. El regalo perfecto para cualquier ocasión.',
    descLarga: 'El Mate Listo es un kit completo listo para matear desde el primer momento. Incluye mate, bombilla y yerba. El regalo perfecto para quienes quieren empezar o para sorprender a un mateador.',
    img: 'img/catalogo/Mate listo/IMG_1097.jpg',
    imgs: [],
    badge: 'Ideal regalo',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Mate%20Listo'
  },
{
    id: 'bolso-galope',
    nombre: 'Bolso Galope',
    categoria: 'accesorio',
    catLabel: 'Bolso',
    precio: '$28.900',
    desc: 'Bolso de cuero con estilo galope. Compartimentos para mate, termo y accesorios.',
    descLarga: 'El Bolso Galope es de cuero con estilo galope y múltiples compartimentos internos. Para llevar mate, termo y todos los accesorios con comodidad y estilo.',
    img: 'img/catalogo/Bolso Galope/IMG_1077.jpg',
    imgs: ['img/catalogo/Bolso Galope/IMG_1078.jpg','img/catalogo/Bolso Galope/IMG_1079.jpg','img/catalogo/Bolso Galope/IMG_9516.jpg','img/catalogo/Bolso Galope/IMG_9528.jpg'],
    badge: null,
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20el%20Bolso%20Galope'
  },
{
    id: 'luz-mate',
    nombre: 'Luz para Mate',
    categoria: 'accesorio',
    catLabel: 'Accesorio',
    precio: '$5.500',
    desc: 'Iluminación LED especial para matear en la oscuridad. Original y funcional.',
    descLarga: 'La Luz para Mate es una iluminación LED especial que se acopla al mate para usarlo en la oscuridad. Original, funcional y un regalo distinto.',
    img: 'img/catalogo/Luz para mate/IMG_1095.PNG',
    imgs: [],
    badge: 'Único',
    badgeVariant: null,
    waMsg: 'Hola%2C%20quiero%20consultar%20por%20la%20Luz%20para%20Mate'
  }
];

// ── Funciones globales para acceder a los datos ────────────

/** Busca un producto por ID */
function getProductoById(id) {
  return PRODUCTOS.find(p => p.id === id);
}

/** Devuelve productos de la misma categoría */
function getRelacionados(categoria, excludeId = null, limit = 4) {
  return PRODUCTOS
    .filter(p => p.categoria === categoria && p.id !== excludeId)
    .slice(0, limit);
}
